// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Models.Migrations
{
    [DbContext(typeof(WatchContext))]
    [Migration("20230503115520_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.3.23174.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.Session", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<int>("AvgHeartRate")
                        .HasColumnType("integer")
                        .HasColumnName("avg_heart_rate");

                    b.Property<short>("PoolLaps")
                        .HasColumnType("smallint")
                        .HasColumnName("pool_laps");

                    b.Property<short>("PoolLeght")
                        .HasColumnType("smallint")
                        .HasColumnName("pool_lenght");

                    b.Property<int>("SessionDistance")
                        .HasColumnType("integer")
                        .HasColumnName("session_distance");

                    b.Property<TimeSpan>("SessionTime")
                        .HasColumnType("interval")
                        .HasColumnName("session_time");

                    b.HasKey("SessionId");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("sessions", "pw_gruppo1");
                });

            modelBuilder.Entity("Models.Smartwatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("HeartRate")
                        .HasColumnType("integer")
                        .HasColumnName("heart_rate");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("position");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("smartwatches", "pw_gruppo1");
                });
#pragma warning restore 612, 618
        }
    }
}
